#System
max_workers: 6

# DB CONFIGURATION
DB_USERNAME: usuario
DB_PASSWORD: clave
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: BioData

# Uniprot Extraction
search_criteria: '(structure_3d:true) AND (reviewed:true)'
limit: 100

# PDB Extraction
resolution_threshold: 2.5
server: "https://files.wwpdb.org/"
pdb_path: "/home/frapercan/data/pdb"
pdb_chains_path: "/home/frapercan/data/chains"
file_format: "mmCif"


# Sequence Clustering
fasta_path: "/home/frapercan/data/complete.fasta"
cdhit_out_path: "/home/frapercan/data/out"
sequence_identity_threshold: 0.95
memory_usage: 25000


data_dir: /opt/shared/FASTA
output_dir: /opt/shared/FASTA/output
merge_name: merge_25
