#System
max_workers: 15

# DB CONFIGURATION
DB_USERNAME: usuario
DB_PASSWORD: clave
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: BioData

# Uniprot Extraction
search_criteria: '(structure_3d:true) AND (reviewed:true)'
limit: 100

resolution_threshold: 2.5
data_dir: /opt/shared/FASTA
output_dir: /opt/shared/FASTA/output
merge_name: merge_25
