#System
max_workers: 18

# DB CONFIGURATION
DB_USERNAME: usuario
DB_PASSWORD: clave
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: BioData





# Uniprot Extraction
search_criteria: '(structure_3d:true)'
limit: 100

# PDB Extraction
resolution_threshold: 2.5
server: "https://files.wwpdb.org/"
pdb_path: "/home/frapercan/data/pdb"
pdb_chains_path: "/home/frapercan/data/chains"
file_format: "mmCif"

# NMR
allow_multiple_chain_models: False

# Sequence Clustering
fasta_path: "/home/frapercan/data/complete.fasta"
cdhit_out_path: "/home/frapercan/data/out"
sequence_identity_threshold: 0.95
alignment_coverage: 0.95
memory_usage: 25000
most_representative_search: 1

force_representatives: "/home/frapercan/data/input_data/metamorphic_pairs.csv"



#CE-Align
retry_timeout: 1
retry_count: 25
batch_size: 1000
task_timeout: 3

