#System
max_workers: 25
binaries_path: '../binaries'

# DB CONFIGURATION
DB_USERNAME: usuario
DB_PASSWORD: clave
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: BioData

## Information System/
# Uniprot Extraction

load_accesion_csv: ../data/uniprot_ids.csv
load_accesion_column: ID
tag: 'GOA'

search_criteria: '(taxonomy_id:212035) AND (structure_3d:true)'
limit: 100

# PDB Extraction
resolution_threshold: 20
server: "https://files.wwpdb.org/"
pdb_path: "/home/frapercan/data/pdb"
pdb_chains_path: "/home/frapercan/data/chains"
file_format: "mmCif"
allow_multiple_chain_models: False # NMR

## Operations
constants: "config/constants.yaml"

# Sequence Clustering
fasta_path: "/home/frapercan/data/complete.fasta"
cdhit_out_path: "/home/frapercan/data/out"
sequence_identity_threshold: 0.95
alignment_coverage: 0.95
memory_usage: 25000
most_representative_search: 1

# Structural Alignment
structural_alignment:
  types:
    - 1
    - 2
    - 3

  retry_timeout: 1
  retry_count: 5
  batch_size: 1000
  task_timeout: 20


# Embedding
embedding:
  types:
#    - 1 # ESM
    - 2 # Prost

# GO Metrics
obo: '../data/go-basic.obo'
go_annotation_file: '../data/cgd.gaf'

allowed_evidences:
  - EXP
  - IDA
  - IPI
  - IMP
  - IGI
  - IEP
  - TAS
  - IC

k: 5

