DB_USERNAME: usuario
DB_PASSWORD: clave
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: BioData

resolution_threshold: 2.5
max_workers: 15
data_dir: /opt/shared/FASTA
output_dir: /opt/shared/FASTA/output
merge_name: merge_25

pdb_dir: /media/frapercan/DATA 2/metamorphisms/PDB_test
chain_dir: /media/frapercan/DATA 2/metamorphisms/chains



identity_threshold: 0.95